version: "2"
services:
  mongodb:
    image: "mongo:4.4.24"
    ports:
      - "127.0.0.1:47017:27017"
    volumes:
      - "./psydb-data-volume/mongodb:/data/db"
    networks:
      - "psydb-net"

  nginx-reverse:
    image: "nginx:1.25.2"
    ports:
      - "80:80"
    volumes:
      - "./psydb-config-volume/nginx:/etc/nginx/conf.d"
    networks:
      - "psydb-net"
    # make it accessible from the host machine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - psydb

  # remove if using an actual mail server
  mailhog:
    image: "mailhog/mailhog"
    ports:
      - "127.0.0.1:1025:1025"
      - "8025:8025"
    networks:
      - "psydb-net"
    # make it accessible from the host machine
    extra_hosts:
      - "host.docker.internal:host-gateway"

  psydb:
    image: "cdxoo/psydb:0.1.0-alpha.202304120434"
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "./psydb-config-volume/psydb:/usr/src/app/config"
    networks:
      - "psydb-net"
    depends_on:
      - mongodb
      - mailhog

networks:
  psydb-net:
    driver: "bridge"

