'use strict';
var {
    isArray, isPlainObject,
    pathify, jsonpointer
} = require('@mpieva/psydb-core-utils');

// NOTE: dont know where to put right now

var cleanValues = (bag) => {
    var { from: that, value: targetValue } = bag;
    if (isArray(that)) {
        var out = [];
        for (var it of that) {
            if (it !== targetValue) {
                out.push(cleanValues({ from: it, value: targetValue }))
            }
        }
        return out;
    }
    else if (isPlainObject(that)) {
        var out = {};
        for (var [ key, value ] of Object.entries(that)) {
            if (value !== targetValue) {
                out[key] = cleanValues({ from: value, value: targetValue });
            }
        }
        return out;
    }
    else {
        return that;
    }
}

var PROPS_AS_STATE = (payload, options = {}) => {
    // NOTE: "extraState" is maybe not the best phrase to use as it
    // is actually state that is auto generated by the backend and not
    // existant in the payload per se, but might be overridden by
    // values in the payload
    // ovverrides on the other hand are values that exist in the palyoad
    // but are overridden by the backend (not sure what that would be
    // at this point but its concievable that this could happen)
    var {
        extraState = {}, overrides = {},
        //flatten = false
    } = options;

    var { props, ...rest } = cleanValues({ from: payload, value: null });
   
    var todo = [
        ...Object.entries(extraState),
        ...Object.entries(pathify(props, {
            delimiter: '/', prefix: '', traverseArrays: true
        })),
        ...Object.entries(overrides),
    ]

    var out = { ...rest, state: {}};
    for (var [ptr, value] of todo) {
        jsonpointer.set(out.state, ptr, value);
    }

    return out;
    
    //return (
    //    flatten
    //    ? pathify(out, { delimiter: '/', prefix: '', traverseArray: true })
    //    : out
    //);
}

var KOA_BODY = async (promise) => {
    var koaContext = await promise;
    return koaContext.response.body;
}
var KOA_BODYDATA = async (promise) => {
    var koaContext = await promise;
    return koaContext.response.body.data;
}
var KOA_BODYRECORD = async (promise) => {
    var koaContext = await promise;
    return koaContext.response.body.data.record;
}

var KOA_CHANNELS = async (promise) => {
    var koaContext = await promise;
    //console.log(koaContext.response);
    //return koaContext.response.body.data
    return koaContext.modifiedChannels; // FIXME
}

//var KOA_CSV = async (promise) => {
//    var koaContext = await promise;
//
//    var { type, body } = koaContext.response;
//    var decoded = iconv.decode(Buffer.from(body), 'windows-1252');
//
//    return { type, body, decoded }
//}

module.exports = {
    PROPS_AS_STATE,
    KOA_BODY,
    KOA_BODYDATA,
    KOA_BODYRECORD,

    KOA_CHANNELS,
    //KOA_CSV,
}
